[package]
name = "f2m"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
log = "0.4.22"
noodles = { version = "0.77.0", features = ["async", "bed", "core", "tabix"] }
pretty_env_logger = "0.5.0"
